baseurl: portfolio # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

title: Full Stack Developer
description: Full Stack Developer and UX Developer
author: Appu Yadav
lang: en

# facebook:
#   app_id: 1234
#   publisher: 1234
#   admins: 1234

# twitter:
#   username: benbalter
#   card: summary

# webmaster_verifications:
#   google: 1234
#   bing: 1234
#   alexa: 1234
#   yandex: 1234
#   baidu: 1234

social:
  name: Roger the Racoon
  links: https://twitter.com/BenBalter

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  #   - .sass-cache/
  #   - .jekyll-cache/
  #   - gemfiles/
  - Gemfile
  - Gemfile.lock
  #   - node_modules/
  #   - vendor/bundle/
  #   - vendor/cache/
  #   - vendor/gems/
  #   - vendor/ruby/
  - vendor
