#-------------------------------------------------
# General Site Settings

title: Full Stack Developer
logo: loho.png
email: appu.response@gmail.com
phone: +91 8655909568
address: Bhayander Mumbai, Maharatra, India


menu:
- { name: Home, link: '#home' }
- { name: Service, link: '#service' }
- { name: Portfolio, link: '#portfolio' }
- { name: Resume, link: '#resume' }
- { name: Skills, link: '#skills' }
- { name: Contact, link: '#contact' }


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Home Section

home:
  home-name: Appu Yadav
  home-title-desc: A full stack all around designer that may or may not include a guide for specific creative potential methods who framing and evaluating moves.
  social:
    - { name: "LINKEDIN", link: "https://www.linkedin.com/in/appu-yadav-190260141/" }
    - { name: "TWITTER", link: "https://twitter.com/appu_gaurav" }
    - { name: "INSTAGRAM", link: "https://www.instagram.com/appu2821/" }
    - { name: "FACEBOOK", link: "https://www.facebook.com/profile.php?id=100008435251536&ref=bookmarks" }
    - { name: "GITHUB", link: "https://github.com/AppuYadav" }

#---------------------------------
# Header menu

header:
  menu:
    - { name: "Home", href: "home" }
    - { name: "Service", href: "service" }
    - { name: "Portfolio", href: "portfolio" }
    - { name: "Resume", href: "resume" }
    - { name: "Skills", href: "skills" }
    - { name: "Blog", href: "blog" }
    - { name: "Contact", href: "contact" }

#-------------------------------------
# Developer Info

developer-info: {
  name: Appu Yadav,
  role: Full Stack Developer,
  email: appu.response@gmail.com,
  phone: 8655909568,
  address: Bhayander Mumbai, Maharashtra, India
}

#-------------------------------------
# Service Section


services:
  service:
    - { class: "service-holder", image: "assets/images/service1.png", title: "Design", title-info: "Tellus pharetra erat tristique erat donec dignissim etiam sed malesik enim sodales lorem ipsum" }
    - { class: "service-holder m-right-0", image: "assets/images/service2.png", title: "Develop", title-info: "Tellus pharetra erat tristique erat donec dignissim etiam sed malesik enim sodales lorem ipsum" }
    - { class: "service-holder m-bottom-0", image: "assets/images/service3.png", title: "Write", title-info: "Vestibulum consequat, dignissim tellus sollicitudin vulputate elit aliquet ullamcorper feugiat nisi" }
    - { class: "service-holder m-right-0 m-bottom-0", image: "assets/images/service4.png", title: "Promote", title-info: "Quam facilisi nunc faucibus at porttitor vestibulum consequat dignissim tellus sollicitudin" }
